// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-V_FaJj7W_JARYJ5RDXhQ6kG3UA936c',
    appId: '1:696457965956:web:9a79a7adca5106b2e0add1',
    messagingSenderId: '696457965956',
    projectId: 'mynotesfluttersampleproject',
    authDomain: 'mynotesfluttersampleproject.firebaseapp.com',
    storageBucket: 'mynotesfluttersampleproject.appspot.com',
    measurementId: 'G-KN3B386BT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0rEx2v-qsGZF9t6DmWvkB-xVK-0Ne08',
    appId: '1:696457965956:android:5fee562055e17e12e0add1',
    messagingSenderId: '696457965956',
    projectId: 'mynotesfluttersampleproject',
    storageBucket: 'mynotesfluttersampleproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIc08z_Sfw5QD5-8x6_FI9gmtUoxcTGsw',
    appId: '1:696457965956:ios:b1bd1b1cb228f230e0add1',
    messagingSenderId: '696457965956',
    projectId: 'mynotesfluttersampleproject',
    storageBucket: 'mynotesfluttersampleproject.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIc08z_Sfw5QD5-8x6_FI9gmtUoxcTGsw',
    appId: '1:696457965956:ios:b04f50e373bd3429e0add1',
    messagingSenderId: '696457965956',
    projectId: 'mynotesfluttersampleproject',
    storageBucket: 'mynotesfluttersampleproject.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
